name: Apply edits from issue comments

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check trigger
        id: check
        run: |
          BODY="${{ github.event.comment.body }}"
          if [[ "$BODY" == /apply* ]]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Extract file path and content
        if: steps.check.outputs.run == 'true'
        run: |
          BODY=$(printf "%s" "${{ github.event.comment.body }}" | tr -d '\r')
          FILE=$(printf "%s" "$BODY" | head -n1 | awk '{print $2}')
          echo "Target file: $FILE"
          mkdir -p "$(dirname "$FILE")"
          printf "%s\n" "$BODY" | sed '1d' | sed '/^```/d' > "$FILE"

      - name: Commit changes
        if: steps.check.outputs.run == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Applied fix from issue comment by ${{ github.event.comment.user.login }}"
          git push origin HEAD:main
