name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Syntax check (py_compile)
      run: |
        python - <<'PY'
        import os, py_compile, sys
        failed = []
        for root, _, files in os.walk('.'):
            for f in files:
                if f.endswith('.py'):
                    p = os.path.join(root, f)
                    try:
                        py_compile.compile(p, doraise=True)
                    except Exception as e:
                        print(f"ERROR in {p}: {e}")
                        failed.append(p)
        if failed:
            sys.exit(1)
        print("✅ OK: syntax looks good.")
        PY

    - name: Install flake8 and pytest
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 . || echo "⚠️ Lint warnings found"

    - name: Run pytest
      run: |
        pytest || echo "⚠️ Tests failed (or none found)"
