name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax check (py_compile on all .py files)
        run: |
          python - <<'PY'
          import os, py_compile, sys
          failed = []
          for root, _, files in os.walk('.'):
              for f in files:
                  if f.endswith('.py'):
                      p = os.path.join(root, f)
                      try:
                          py_compile.compile(p, doraise=True)
                      except Exception as e:
                          print(f"ERROR in {p}: {e}")
                          failed.append(p)
          if failed:
              sys.exit(1)
          print("OK: syntax looks good.")
          PY
